require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/captured_pokemons", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # CapturedPokemon. As you add validations to CapturedPokemon, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      CapturedPokemon.create! valid_attributes
      get captured_pokemons_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      captured_pokemon = CapturedPokemon.create! valid_attributes
      get captured_pokemon_url(captured_pokemon)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_captured_pokemon_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      captured_pokemon = CapturedPokemon.create! valid_attributes
      get edit_captured_pokemon_url(captured_pokemon)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new CapturedPokemon" do
        expect {
          post captured_pokemons_url, params: { captured_pokemon: valid_attributes }
        }.to change(CapturedPokemon, :count).by(1)
      end

      it "redirects to the created captured_pokemon" do
        post captured_pokemons_url, params: { captured_pokemon: valid_attributes }
        expect(response).to redirect_to(captured_pokemon_url(CapturedPokemon.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new CapturedPokemon" do
        expect {
          post captured_pokemons_url, params: { captured_pokemon: invalid_attributes }
        }.to change(CapturedPokemon, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post captured_pokemons_url, params: { captured_pokemon: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested captured_pokemon" do
        captured_pokemon = CapturedPokemon.create! valid_attributes
        patch captured_pokemon_url(captured_pokemon), params: { captured_pokemon: new_attributes }
        captured_pokemon.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the captured_pokemon" do
        captured_pokemon = CapturedPokemon.create! valid_attributes
        patch captured_pokemon_url(captured_pokemon), params: { captured_pokemon: new_attributes }
        captured_pokemon.reload
        expect(response).to redirect_to(captured_pokemon_url(captured_pokemon))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        captured_pokemon = CapturedPokemon.create! valid_attributes
        patch captured_pokemon_url(captured_pokemon), params: { captured_pokemon: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested captured_pokemon" do
      captured_pokemon = CapturedPokemon.create! valid_attributes
      expect {
        delete captured_pokemon_url(captured_pokemon)
      }.to change(CapturedPokemon, :count).by(-1)
    end

    it "redirects to the captured_pokemons list" do
      captured_pokemon = CapturedPokemon.create! valid_attributes
      delete captured_pokemon_url(captured_pokemon)
      expect(response).to redirect_to(captured_pokemons_url)
    end
  end
end
