default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: parcial_1_development

test:
  <<: *default
  database: parcial_1_test

production:
  <<: *default
  database: parcial_1_production
  username: parcial_1
  password: <%= ENV["LENGUAJES_1_DATABASE_PASSWORD"] %>
