PokemonTrainer.create!(first_name: "Carlos", last_name: "Escami", region: "Kanto", id_number: "88888888", level: 2)
PokemonTrainer.create!(first_name: "Angel", last_name: "Amaya", region: "Argentina", id_number: "23456789", level: 0)
PokemonTrainer.create!(first_name: "Andy", last_name: "Ramirez", region: "Ciudad Paleta", id_number: "34567812", level: 1)
PokemonTrainer.create!(first_name: "Rafael", last_name: "Ramos", region: "Venecia", id_number: "12345789", level: 2)
PokemonTrainer.create!(first_name: "Miguel", last_name: "Pelaes", region: "Grecia", id_number: "93451891", level: 2)
PokemonTrainer.create!(first_name: "Fernando", last_name: "Rímolo", region: "Pueblo Algo", id_number: "67676767", level: 1)